// Cubos del Censo 2020 (ITER) con el resto de los indicadores: características de la población (iter_2: edades 70+,
// fecundidad, migración, lengua indígena, afrodescendencia, discapacidad, educación) y hogares y vivienda (iter_3: PEA,
// salud, estado conyugal, religión, hogares, viviendas y sus servicios). Mismo universo y jerarquía que el cubo de población.
import type { Cubo, Dimension } from "../tipos";

const FUENTE = { fuente: "INEGI — Censo de Población y Vivienda 2020, Principales resultados por localidad (ITER)", fuente_url: "https://www.inegi.org.mx/programas/ccpv/2020/", licencia: "Términos de libre uso INEGI" };
const DIMS: Dimension[] = [
  { clave: "entidad", titulo: "Entidad", id: "i.entidad", nombre: "i.nom_ent", tipo: "geografica", geo: "entidad" },
  { clave: "municipio", titulo: "Municipio", id: "i.entidad || i.mun", nombre: "i.nom_mun", tipo: "geografica", geo: "municipio", padre: "entidad" },
  { clave: "localidad", titulo: "Localidad", id: "i.entidad || i.mun || i.loc", nombre: "i.nom_loc", tipo: "geografica", geo: "localidad", padre: "municipio" },
];
// A diferencia de la población total, en estas tablas el INEGI suprime (*) los valores de las localidades de una y dos
// viviendas y los publica agregados por municipio en las filas 9998/9999; por eso aquí esas filas SÍ forman parte del
// universo (verificado: Aguascalientes PEA 706,930 y HLI 2,539 = fila total de la entidad). Aun así, en 29 entidades la suma
// queda por debajo de la fila total en fracciones de un punto porcentual (hogares: 35,213,375 contra 35,219,141 en el país,
// 0.016 %): son cifras que el INEGI suprime por confidencialidad en otras localidades pequeñas y no publica en ningún renglón.
const NOTAS = ["Una fila por localidad más, por municipio, los agregados de localidades de una y dos viviendas (claves 9998 y 9999) que llevan las cifras que el INEGI suprime en esas localidades; así las sumas por entidad reproducen las filas totales del ITER salvo por cifras suprimidas por confidencialidad en otras localidades pequeñas (diferencia medida: 0.016 % de los hogares a nivel nacional; Aguascalientes cuadra exacto).", "Valores confidenciales (*) del ITER se conservan como nulos y no suman."];
const DONDE = "i.mun <> '000' AND i.loc <> '0000'";

export const CENSO_CARACTERISTICAS: Cubo = {
  clave: "censo2020-caracteristicas", nombre: "Características de la población (Censo 2020)", tema: "poblacion", ...FUENTE,
  descripcion: "Población de 70 años y más, fecundidad, lugar de nacimiento y residencia en 2015, lengua indígena, afrodescendencia, discapacidad y limitaciones, asistencia escolar y escolaridad, por localidad, municipio y entidad.",
  binding: "DB_CENSO2020", desde: "iter_2 x JOIN iter i ON i.entidad = x.entidad AND i.mun = x.mun AND i.loc = x.loc", donde: DONDE,
  medidas: [
  { clave: "p_70a74_m", titulo: "Población masculina de 70 a 74 años", sql: "SUM(x.p_70a74_m)", unidad: "personas", sumable: true },
  { clave: "p_75a79", titulo: "Población de 75 a 79 años", sql: "SUM(x.p_75a79)", unidad: "personas", sumable: true },
  { clave: "p_75a79_f", titulo: "Población femenina de 75 a 79 años", sql: "SUM(x.p_75a79_f)", unidad: "personas", sumable: true },
  { clave: "p_75a79_m", titulo: "Población masculina de 75 a 79 años", sql: "SUM(x.p_75a79_m)", unidad: "personas", sumable: true },
  { clave: "p_80a84", titulo: "Población de 80 a 84 años", sql: "SUM(x.p_80a84)", unidad: "personas", sumable: true },
  { clave: "p_80a84_f", titulo: "Población femenina de 80 a 84 años", sql: "SUM(x.p_80a84_f)", unidad: "personas", sumable: true },
  { clave: "p_80a84_m", titulo: "Población masculina de 80 a 84 años", sql: "SUM(x.p_80a84_m)", unidad: "personas", sumable: true },
  { clave: "p_85ymas", titulo: "Población de 85 años y más", sql: "SUM(x.p_85ymas)", unidad: "personas", sumable: true },
  { clave: "p_85ymas_f", titulo: "Población femenina de 85 años y más", sql: "SUM(x.p_85ymas_f)", unidad: "personas", sumable: true },
  { clave: "p_85ymas_m", titulo: "Población masculina de 85 años y más", sql: "SUM(x.p_85ymas_m)", unidad: "personas", sumable: true },
  { clave: "prom_hnv", titulo: "Promedio de hijas e hijos nacidos vivos", sql: "AVG(x.prom_hnv)", unidad: "promedio", sumable: false, decimales: 2, descripcion: "Promedio simple de los promedios por localidad (no ponderado): úselo por localidad." },
  { clave: "pnacent", titulo: "Población nacida en la entidad", sql: "SUM(x.pnacent)", unidad: "personas", sumable: true },
  { clave: "pnacent_f", titulo: "Población femenina nacida en la entidad", sql: "SUM(x.pnacent_f)", unidad: "personas", sumable: true },
  { clave: "pnacent_m", titulo: "Población masculina nacida en la entidad", sql: "SUM(x.pnacent_m)", unidad: "personas", sumable: true },
  { clave: "pnacoe", titulo: "Población nacida en otra entidad", sql: "SUM(x.pnacoe)", unidad: "personas", sumable: true },
  { clave: "pnacoe_f", titulo: "Población femenina nacida en otra entidad", sql: "SUM(x.pnacoe_f)", unidad: "personas", sumable: true },
  { clave: "pnacoe_m", titulo: "Población masculina nacida en otra entidad", sql: "SUM(x.pnacoe_m)", unidad: "personas", sumable: true },
  { clave: "pres2015", titulo: "Población de 5 años y más residente en la entidad en marzo de 2015", sql: "SUM(x.pres2015)", unidad: "personas", sumable: true },
  { clave: "pres2015_f", titulo: "Población femenina de 5 años y más residente en la entidad en marzo de 2015", sql: "SUM(x.pres2015_f)", unidad: "personas", sumable: true },
  { clave: "pres2015_m", titulo: "Población masculina de 5 años y más residente en la entidad en marzo de 2015", sql: "SUM(x.pres2015_m)", unidad: "personas", sumable: true },
  { clave: "presoe15", titulo: "Población de 5 años y más residente en otra entidad en marzo de 2015", sql: "SUM(x.presoe15)", unidad: "personas", sumable: true },
  { clave: "presoe15_f", titulo: "Población femenina de 5 años y más residente en otra entidad en marzo de 2015", sql: "SUM(x.presoe15_f)", unidad: "personas", sumable: true },
  { clave: "presoe15_m", titulo: "Población masculina de 5 años y más residente en otra entidad en marzo de 2015", sql: "SUM(x.presoe15_m)", unidad: "personas", sumable: true },
  { clave: "p3ym_hli", titulo: "Población de 3 años y más que habla alguna lengua indígena", sql: "SUM(x.p3ym_hli)", unidad: "personas", sumable: true },
  { clave: "p3ym_hli_f", titulo: "Población femenina de 3 años y más que habla alguna lengua indígena", sql: "SUM(x.p3ym_hli_f)", unidad: "personas", sumable: true },
  { clave: "p3ym_hli_m", titulo: "Población masculina de 3 años y más que habla alguna lengua indígena", sql: "SUM(x.p3ym_hli_m)", unidad: "personas", sumable: true },
  { clave: "p3hlinhe", titulo: "Población de 3 años y más que habla alguna lengua indígena y no habla español", sql: "SUM(x.p3hlinhe)", unidad: "personas", sumable: true },
  { clave: "p3hlinhe_f", titulo: "Población femenina de 3 años y más que habla alguna lengua indígena y no habla español", sql: "SUM(x.p3hlinhe_f)", unidad: "personas", sumable: true },
  { clave: "p3hlinhe_m", titulo: "Población masculina de 3 años y más que habla alguna lengua indígena y no habla español", sql: "SUM(x.p3hlinhe_m)", unidad: "personas", sumable: true },
  { clave: "p3hli_he", titulo: "Población de 3 años y más que habla alguna lengua indígena y habla español", sql: "SUM(x.p3hli_he)", unidad: "personas", sumable: true },
  { clave: "p3hli_he_f", titulo: "Población femenina de 3 años y más que habla alguna lengua indígena y habla español", sql: "SUM(x.p3hli_he_f)", unidad: "personas", sumable: true },
  { clave: "p3hli_he_m", titulo: "Población masculina de 3 años y más que habla alguna lengua indígena y habla español", sql: "SUM(x.p3hli_he_m)", unidad: "personas", sumable: true },
  { clave: "p5_hli", titulo: "Población de 5 años y más que habla alguna lengua indígena", sql: "SUM(x.p5_hli)", unidad: "personas", sumable: true },
  { clave: "p5_hli_nhe", titulo: "Población de 5 años y más que habla alguna lengua indígena y no habla español", sql: "SUM(x.p5_hli_nhe)", unidad: "personas", sumable: true },
  { clave: "p5_hli_he", titulo: "Población de 5 años y más que habla alguna lengua indígena y habla español", sql: "SUM(x.p5_hli_he)", unidad: "personas", sumable: true },
  { clave: "phog_ind", titulo: "Población en hogares censales indígenas", sql: "SUM(x.phog_ind)", unidad: "personas", sumable: true },
  { clave: "pob_afro", titulo: "Población que se considera afromexicana o afrodescendiente", sql: "SUM(x.pob_afro)", unidad: "personas", sumable: true },
  { clave: "pob_afro_f", titulo: "Población femenina que se considera afromexicana o afrodescendiente", sql: "SUM(x.pob_afro_f)", unidad: "personas", sumable: true },
  { clave: "pob_afro_m", titulo: "Población masculina que se considera afromexicana o afrodescendiente", sql: "SUM(x.pob_afro_m)", unidad: "personas", sumable: true },
  { clave: "pcon_disc", titulo: "Población con discapacidad", sql: "SUM(x.pcon_disc)", unidad: "personas", sumable: true },
  { clave: "pcdisc_mot", titulo: "Población con discapacidad para caminar, subir o bajar", sql: "SUM(x.pcdisc_mot)", unidad: "personas", sumable: true },
  { clave: "pcdisc_vis", titulo: "Población con discapacidad para ver, aun usando lentes", sql: "SUM(x.pcdisc_vis)", unidad: "personas", sumable: true },
  { clave: "pcdisc_leng", titulo: "Población con discapacidad para hablar o comunicarse", sql: "SUM(x.pcdisc_leng)", unidad: "personas", sumable: true },
  { clave: "pcdisc_aud", titulo: "Población con discapacidad para oír, aun usando aparato auditivo", sql: "SUM(x.pcdisc_aud)", unidad: "personas", sumable: true },
  { clave: "pcdisc_mot2", titulo: "Población con discapacidad para vestirse, bañarse o comer", sql: "SUM(x.pcdisc_mot2)", unidad: "personas", sumable: true },
  { clave: "pcdisc_men", titulo: "Población con discapacidad para recordar o concentrarse", sql: "SUM(x.pcdisc_men)", unidad: "personas", sumable: true },
  { clave: "pcon_limi", titulo: "Población con limitación", sql: "SUM(x.pcon_limi)", unidad: "personas", sumable: true },
  { clave: "pclim_csb", titulo: "Población con limitación para caminar, subir o bajar", sql: "SUM(x.pclim_csb)", unidad: "personas", sumable: true },
  { clave: "pclim_vis", titulo: "Población con limitación para ver, aun usando lentes", sql: "SUM(x.pclim_vis)", unidad: "personas", sumable: true },
  { clave: "pclim_haco", titulo: "Población con limitación para hablar o comunicarse", sql: "SUM(x.pclim_haco)", unidad: "personas", sumable: true },
  { clave: "pclim_oaud", titulo: "Población con limitación para oír, aun usando aparato auditivo", sql: "SUM(x.pclim_oaud)", unidad: "personas", sumable: true },
  { clave: "pclim_mot2", titulo: "Población con limitación para vestirse, bañarse o comer", sql: "SUM(x.pclim_mot2)", unidad: "personas", sumable: true },
  { clave: "pclim_re_co", titulo: "Población con limitación para recordar o concentrarse", sql: "SUM(x.pclim_re_co)", unidad: "personas", sumable: true },
  { clave: "pclim_pmen", titulo: "Población con algún problema o condición mental", sql: "SUM(x.pclim_pmen)", unidad: "personas", sumable: true },
  { clave: "psind_lim", titulo: "Población sin discapacidad, limitación, problema o condición mental", sql: "SUM(x.psind_lim)", unidad: "personas", sumable: true },
  { clave: "p3a5_noa", titulo: "Población de 3 a 5 años que no asiste a la escuela", sql: "SUM(x.p3a5_noa)", unidad: "personas", sumable: true },
  { clave: "p3a5_noa_f", titulo: "Población femenina de 3 a 5 años que no asiste a la escuela", sql: "SUM(x.p3a5_noa_f)", unidad: "personas", sumable: true },
  { clave: "p3a5_noa_m", titulo: "Población masculina de 3 a 5 años que no asiste a la escuela", sql: "SUM(x.p3a5_noa_m)", unidad: "personas", sumable: true },
  { clave: "p6a11_noa", titulo: "Población de 6 a 11 años que no asiste a la escuela", sql: "SUM(x.p6a11_noa)", unidad: "personas", sumable: true },
  { clave: "p6a11_noaf", titulo: "Población femenina de 6 a 11 años que no asiste a la escuela", sql: "SUM(x.p6a11_noaf)", unidad: "personas", sumable: true },
  { clave: "p6a11_noam", titulo: "Población masculina de 6 a 11 años que no asiste a la escuela", sql: "SUM(x.p6a11_noam)", unidad: "personas", sumable: true },
  { clave: "p12a14noa", titulo: "Población de 12 a 14 años que no asiste a la escuela", sql: "SUM(x.p12a14noa)", unidad: "personas", sumable: true },
  { clave: "p12a14noaf", titulo: "Población femenina de 12 a 14 años que no asiste a la escuela", sql: "SUM(x.p12a14noaf)", unidad: "personas", sumable: true },
  { clave: "p12a14noam", titulo: "Población masculina de 12 a 14 años que no asiste a la escuela", sql: "SUM(x.p12a14noam)", unidad: "personas", sumable: true },
  { clave: "p15a17a", titulo: "Población de 15 a 17 años que asiste a la escuela", sql: "SUM(x.p15a17a)", unidad: "personas", sumable: true },
  { clave: "p15a17a_f", titulo: "Población femenina de 15 a 17 años que asiste a la escuela", sql: "SUM(x.p15a17a_f)", unidad: "personas", sumable: true },
  { clave: "p15a17a_m", titulo: "Población masculina de 15 a 17 años que asiste a la escuela", sql: "SUM(x.p15a17a_m)", unidad: "personas", sumable: true },
  { clave: "p18a24a", titulo: "Población de 18 a 24 años que asiste a la escuela", sql: "SUM(x.p18a24a)", unidad: "personas", sumable: true },
  { clave: "p18a24a_f", titulo: "Población femenina de 18 a 24 años que asiste a la escuela", sql: "SUM(x.p18a24a_f)", unidad: "personas", sumable: true },
  { clave: "p18a24a_m", titulo: "Población masculina de 18 a 24 años que asiste a la escuela", sql: "SUM(x.p18a24a_m)", unidad: "personas", sumable: true },
  { clave: "p8a14an", titulo: "Población de 8 a 14 años que no sabe leer y escribir", sql: "SUM(x.p8a14an)", unidad: "personas", sumable: true },
  { clave: "p8a14an_f", titulo: "Población femenina de 8 a 14 años que no sabe leer y escribir", sql: "SUM(x.p8a14an_f)", unidad: "personas", sumable: true },
  { clave: "p8a14an_m", titulo: "Población masculina de 8 a 14 años que no sabe leer y escribir", sql: "SUM(x.p8a14an_m)", unidad: "personas", sumable: true },
  { clave: "p15ym_an", titulo: "Población de 15 años y más analfabeta", sql: "SUM(x.p15ym_an)", unidad: "personas", sumable: true },
  { clave: "p15ym_an_f", titulo: "Población femenina de 15 años y más analfabeta", sql: "SUM(x.p15ym_an_f)", unidad: "personas", sumable: true },
  { clave: "p15ym_an_m", titulo: "Población masculina de 15 años y más analfabeta", sql: "SUM(x.p15ym_an_m)", unidad: "personas", sumable: true },
  { clave: "p15ym_se", titulo: "Población de 15 años y más sin escolaridad", sql: "SUM(x.p15ym_se)", unidad: "personas", sumable: true },
  { clave: "p15ym_se_f", titulo: "Población femenina de 15 años y más sin escolaridad", sql: "SUM(x.p15ym_se_f)", unidad: "personas", sumable: true },
  { clave: "p15ym_se_m", titulo: "Población masculina de 15 años y más sin escolaridad", sql: "SUM(x.p15ym_se_m)", unidad: "personas", sumable: true },
  { clave: "p15pri_in", titulo: "Población de 15 años y más con primaria incompleta", sql: "SUM(x.p15pri_in)", unidad: "personas", sumable: true },
  { clave: "p15pri_inf", titulo: "Población femenina de 15 años y más con primaria incompleta", sql: "SUM(x.p15pri_inf)", unidad: "personas", sumable: true },
  { clave: "p15pri_inm", titulo: "Población masculina de 15 años y más con primaria incompleta", sql: "SUM(x.p15pri_inm)", unidad: "personas", sumable: true },
  { clave: "p15pri_co", titulo: "Población de 15 años y más con primaria completa", sql: "SUM(x.p15pri_co)", unidad: "personas", sumable: true },
  { clave: "p15pri_cof", titulo: "Población femenina de 15 años y más con primaria completa", sql: "SUM(x.p15pri_cof)", unidad: "personas", sumable: true },
  { clave: "p15pri_com", titulo: "Población masculina de 15 años y más con primaria completa", sql: "SUM(x.p15pri_com)", unidad: "personas", sumable: true },
  { clave: "p15sec_in", titulo: "Población de 15 años y más con secundaria incompleta", sql: "SUM(x.p15sec_in)", unidad: "personas", sumable: true },
  { clave: "p15sec_inf", titulo: "Población femenina de 15 años y más con secundaria incompleta", sql: "SUM(x.p15sec_inf)", unidad: "personas", sumable: true },
  { clave: "p15sec_inm", titulo: "Población masculina de 15 años y más con secundaria incompleta", sql: "SUM(x.p15sec_inm)", unidad: "personas", sumable: true },
  { clave: "p15sec_co", titulo: "Población de 15 años y más con secundaria completa", sql: "SUM(x.p15sec_co)", unidad: "personas", sumable: true },
  { clave: "p15sec_cof", titulo: "Población femenina de 15 años y más con secundaria completa", sql: "SUM(x.p15sec_cof)", unidad: "personas", sumable: true },
  { clave: "p15sec_com", titulo: "Población masculina de 15 años y más con secundaria completa", sql: "SUM(x.p15sec_com)", unidad: "personas", sumable: true },
  { clave: "p18ym_pb", titulo: "Población de 18 años y más con educación posbásica", sql: "SUM(x.p18ym_pb)", unidad: "personas", sumable: true },
  { clave: "p18ym_pb_f", titulo: "Población femenina de 18 años y más con educación posbásica", sql: "SUM(x.p18ym_pb_f)", unidad: "personas", sumable: true },
  { clave: "p18ym_pb_m", titulo: "Población masculina de 18 años y más con educación posbásica", sql: "SUM(x.p18ym_pb_m)", unidad: "personas", sumable: true },
  { clave: "graproes", titulo: "Grado promedio de escolaridad", sql: "AVG(x.graproes)", unidad: "promedio", sumable: false, decimales: 2, descripcion: "Promedio simple de los promedios por localidad (no ponderado): úselo por localidad." },
  { clave: "graproes_f", titulo: "Grado promedio de escolaridad de la población femenina", sql: "AVG(x.graproes_f)", unidad: "promedio", sumable: false, decimales: 2, descripcion: "Promedio simple de los promedios por localidad (no ponderado): úselo por localidad." },
  { clave: "graproes_m", titulo: "Grado promedio de escolaridad de la población masculina", sql: "AVG(x.graproes_m)", unidad: "promedio", sumable: false, decimales: 2, descripcion: "Promedio simple de los promedios por localidad (no ponderado): úselo por localidad." },  ],
  dimensiones: DIMS, predeterminado: { medidas: ["p3ym_hli", "pcon_disc"], columnas: ["entidad"] }, sql_corte: "SELECT '2020-03-15' AS corte", notas: NOTAS, api_dominio: "/api/v1/censo2020",
};
export const CENSO_HOGARES: Cubo = {
  clave: "censo2020-hogares-vivienda", nombre: "Trabajo, salud, hogares y vivienda (Censo 2020)", tema: "poblacion", ...FUENTE,
  descripcion: "Población económicamente activa y ocupada, afiliación a servicios de salud, estado conyugal, religión, hogares por sexo de la jefatura, viviendas y sus materiales, servicios y bienes, por localidad, municipio y entidad.",
  binding: "DB_CENSO2020", desde: "iter_3 x JOIN iter i ON i.entidad = x.entidad AND i.mun = x.mun AND i.loc = x.loc", donde: DONDE,
  medidas: [
  { clave: "pea", titulo: "Población de 12 años y más económicamente activa", sql: "SUM(x.pea)", unidad: "personas", sumable: true },
  { clave: "pea_f", titulo: "Población femenina de 12 años y más económicamente activa", sql: "SUM(x.pea_f)", unidad: "personas", sumable: true },
  { clave: "pea_m", titulo: "Población masculina de 12 años y más económicamente activa", sql: "SUM(x.pea_m)", unidad: "personas", sumable: true },
  { clave: "pe_inac", titulo: "Población de 12 años y más no económicamente activa", sql: "SUM(x.pe_inac)", unidad: "personas", sumable: true },
  { clave: "pe_inac_f", titulo: "Población femenina de 12 años y más no económicamente activa", sql: "SUM(x.pe_inac_f)", unidad: "personas", sumable: true },
  { clave: "pe_inac_m", titulo: "Población masculina de 12 años y más no económicamente activa", sql: "SUM(x.pe_inac_m)", unidad: "personas", sumable: true },
  { clave: "pocupada", titulo: "Población de 12 años y más ocupada", sql: "SUM(x.pocupada)", unidad: "personas", sumable: true },
  { clave: "pocupada_f", titulo: "Población femenina de 12 años y más ocupada", sql: "SUM(x.pocupada_f)", unidad: "personas", sumable: true },
  { clave: "pocupada_m", titulo: "Población masculina de 12 años y más ocupada", sql: "SUM(x.pocupada_m)", unidad: "personas", sumable: true },
  { clave: "pdesocup", titulo: "Población de 12 años y más desocupada", sql: "SUM(x.pdesocup)", unidad: "personas", sumable: true },
  { clave: "pdesocup_f", titulo: "Población femenina de 12 años y más desocupada", sql: "SUM(x.pdesocup_f)", unidad: "personas", sumable: true },
  { clave: "pdesocup_m", titulo: "Población masculina de 12 años y más desocupada", sql: "SUM(x.pdesocup_m)", unidad: "personas", sumable: true },
  { clave: "psinder", titulo: "Población sin afiliación a servicios de salud", sql: "SUM(x.psinder)", unidad: "personas", sumable: true },
  { clave: "pder_ss", titulo: "Población afiliada a servicios de salud", sql: "SUM(x.pder_ss)", unidad: "personas", sumable: true },
  { clave: "pder_imss", titulo: "Población afiliada a servicios de salud en el IMSS", sql: "SUM(x.pder_imss)", unidad: "personas", sumable: true },
  { clave: "pder_iste", titulo: "Población afiliada a servicios de salud en el ISSSTE", sql: "SUM(x.pder_iste)", unidad: "personas", sumable: true },
  { clave: "pder_istee", titulo: "Población afiliada a servicios de salud en el ISSSTE estatal", sql: "SUM(x.pder_istee)", unidad: "personas", sumable: true },
  { clave: "pafil_pdom", titulo: "Población afiliada a servicios de salud en PEMEX, Defensa o Marina", sql: "SUM(x.pafil_pdom)", unidad: "personas", sumable: true },
  { clave: "pder_segp", titulo: "Población afiliada a servicios de salud en el Instituto de Salud para el Bienestar", sql: "SUM(x.pder_segp)", unidad: "personas", sumable: true },
  { clave: "pder_imssb", titulo: "Población afiliada a servicios de salud en el IMSS BIENESTAR", sql: "SUM(x.pder_imssb)", unidad: "personas", sumable: true },
  { clave: "pafil_ipriv", titulo: "Población afiliada a servicios de salud en una institución privada", sql: "SUM(x.pafil_ipriv)", unidad: "personas", sumable: true },
  { clave: "pafil_otrai", titulo: "Población afiliada a servicios de salud en otra institución", sql: "SUM(x.pafil_otrai)", unidad: "personas", sumable: true },
  { clave: "p12ym_solt", titulo: "Población de 12 años y más soltera o nunca unida", sql: "SUM(x.p12ym_solt)", unidad: "personas", sumable: true },
  { clave: "p12ym_casa", titulo: "Población de 12 años y más casada o unida", sql: "SUM(x.p12ym_casa)", unidad: "personas", sumable: true },
  { clave: "p12ym_sepa", titulo: "Población de 12 años y más que estuvo casada o unida", sql: "SUM(x.p12ym_sepa)", unidad: "personas", sumable: true },
  { clave: "pcatolica", titulo: "Población con religión católica", sql: "SUM(x.pcatolica)", unidad: "personas", sumable: true },
  { clave: "pro_crieva", titulo: "Población con grupo religioso protestante/cristiano evangélico", sql: "SUM(x.pro_crieva)", unidad: "personas", sumable: true },
  { clave: "potras_rel", titulo: "Población con otras religiones diferentes a las anteriores", sql: "SUM(x.potras_rel)", unidad: "personas", sumable: true },
  { clave: "psin_relig", titulo: "Población sin religión o sin adscripción religiosa", sql: "SUM(x.psin_relig)", unidad: "personas", sumable: true },
  { clave: "tothog", titulo: "Total de hogares censales", sql: "SUM(x.tothog)", unidad: "hogares", sumable: true },
  { clave: "hogjef_f", titulo: "Hogares censales con persona de referencia mujer", sql: "SUM(x.hogjef_f)", unidad: "hogares", sumable: true },
  { clave: "hogjef_m", titulo: "Hogares censales con persona de referencia hombre", sql: "SUM(x.hogjef_m)", unidad: "hogares", sumable: true },
  { clave: "pobhog", titulo: "Población en hogares censales", sql: "SUM(x.pobhog)", unidad: "personas", sumable: true },
  { clave: "phogjef_f", titulo: "Población en hogares censales con persona de referencia mujer", sql: "SUM(x.phogjef_f)", unidad: "personas", sumable: true },
  { clave: "phogjef_m", titulo: "Población en hogares censales con persona de referencia hombre", sql: "SUM(x.phogjef_m)", unidad: "personas", sumable: true },
  { clave: "vivtot", titulo: "Total de viviendas", sql: "SUM(x.vivtot)", unidad: "viviendas", sumable: true },
  { clave: "tvivhab", titulo: "Total de viviendas habitadas", sql: "SUM(x.tvivhab)", unidad: "viviendas", sumable: true },
  { clave: "tvivpar", titulo: "Total de viviendas particulares", sql: "SUM(x.tvivpar)", unidad: "viviendas", sumable: true },
  { clave: "vivpar_hab", titulo: "Viviendas particulares habitadas", sql: "SUM(x.vivpar_hab)", unidad: "viviendas", sumable: true },
  { clave: "vivparh_cv", titulo: "Total de viviendas particulares habitadas con características", sql: "SUM(x.vivparh_cv)", unidad: "viviendas", sumable: true },
  { clave: "tvivparhab", titulo: "Total de viviendas particulares habitadas", sql: "SUM(x.tvivparhab)", unidad: "viviendas", sumable: true },
  { clave: "vivpar_des", titulo: "Viviendas particulares deshabitadas", sql: "SUM(x.vivpar_des)", unidad: "viviendas", sumable: true },
  { clave: "vivpar_ut", titulo: "Viviendas particulares de uso temporal", sql: "SUM(x.vivpar_ut)", unidad: "viviendas", sumable: true },
  { clave: "ocupvivpar", titulo: "Ocupantes en viviendas particulares habitadas", sql: "SUM(x.ocupvivpar)", unidad: "viviendas", sumable: true },
  { clave: "prom_ocup", titulo: "Promedio de ocupantes en viviendas particulares habitadas", sql: "AVG(x.prom_ocup)", unidad: "promedio", sumable: false, decimales: 2, descripcion: "Promedio simple de los promedios por localidad (no ponderado): úselo por localidad." },
  { clave: "pro_ocup_c", titulo: "Promedio de ocupantes por cuarto en viviendas particulares habitadas", sql: "AVG(x.pro_ocup_c)", unidad: "promedio", sumable: false, decimales: 2, descripcion: "Promedio simple de los promedios por localidad (no ponderado): úselo por localidad." },
  { clave: "vph_pisodt", titulo: "Viviendas particulares habitadas con piso de material diferente de tierra", sql: "SUM(x.vph_pisodt)", unidad: "viviendas", sumable: true },
  { clave: "vph_pisoti", titulo: "Viviendas particulares habitadas con piso de tierra", sql: "SUM(x.vph_pisoti)", unidad: "viviendas", sumable: true },
  { clave: "vph_1dor", titulo: "Viviendas particulares habitadas con un dormitorio", sql: "SUM(x.vph_1dor)", unidad: "viviendas", sumable: true },
  { clave: "vph_2ymasd", titulo: "Viviendas particulares habitadas con dos dormitorios y más", sql: "SUM(x.vph_2ymasd)", unidad: "viviendas", sumable: true },
  { clave: "vph_1cuart", titulo: "Viviendas particulares habitadas con sólo un cuarto", sql: "SUM(x.vph_1cuart)", unidad: "viviendas", sumable: true },
  { clave: "vph_2cuart", titulo: "Viviendas particulares habitadas con dos cuartos", sql: "SUM(x.vph_2cuart)", unidad: "viviendas", sumable: true },
  { clave: "vph_3ymasc", titulo: "Viviendas particulares habitadas con 3 cuartos y más", sql: "SUM(x.vph_3ymasc)", unidad: "viviendas", sumable: true },
  { clave: "vph_c_elec", titulo: "Viviendas particulares habitadas que disponen de energía eléctrica", sql: "SUM(x.vph_c_elec)", unidad: "viviendas", sumable: true },
  { clave: "vph_s_elec", titulo: "Viviendas particulares habitadas que no disponen de energía eléctrica", sql: "SUM(x.vph_s_elec)", unidad: "viviendas", sumable: true },
  { clave: "vph_aguadv", titulo: "Viviendas particulares habitadas que disponen de agua entubada en el ámbito de la vivienda", sql: "SUM(x.vph_aguadv)", unidad: "viviendas", sumable: true },
  { clave: "vph_aeasp", titulo: "Viviendas particulares habitadas que disponen de agua entubada y se abastecen del servicio público de agua", sql: "SUM(x.vph_aeasp)", unidad: "viviendas", sumable: true },
  { clave: "vph_aguafv", titulo: "Viviendas particulares habitadas que no disponen de agua entubada en el ámbito de la vivienda", sql: "SUM(x.vph_aguafv)", unidad: "viviendas", sumable: true },
  { clave: "vph_tinaco", titulo: "Viviendas particulares habitadas que disponen de tinaco", sql: "SUM(x.vph_tinaco)", unidad: "viviendas", sumable: true },
  { clave: "vph_cister", titulo: "Viviendas particulares habitadas que disponen de cisterna o aljibe", sql: "SUM(x.vph_cister)", unidad: "viviendas", sumable: true },
  { clave: "vph_excsa", titulo: "Viviendas particulares habitadas que disponen de excusado o sanitario", sql: "SUM(x.vph_excsa)", unidad: "viviendas", sumable: true },
  { clave: "vph_letr", titulo: "Viviendas particulares habitadas que disponen de letrina (pozo u hoyo)", sql: "SUM(x.vph_letr)", unidad: "viviendas", sumable: true },
  { clave: "vph_drenaj", titulo: "Viviendas particulares habitadas que disponen de drenaje", sql: "SUM(x.vph_drenaj)", unidad: "viviendas", sumable: true },
  { clave: "vph_nodren", titulo: "Viviendas particulares habitadas que no disponen de drenaje", sql: "SUM(x.vph_nodren)", unidad: "viviendas", sumable: true },
  { clave: "vph_c_serv", titulo: "Viviendas particulares habitadas que disponen de energía eléctrica, agua entubada de la red pública y drenaje", sql: "SUM(x.vph_c_serv)", unidad: "viviendas", sumable: true },
  { clave: "vph_ndeaed", titulo: "Viviendas particulares habitadas que no disponen de energía eléctrica, agua entubada, ni drenaje", sql: "SUM(x.vph_ndeaed)", unidad: "viviendas", sumable: true },
  { clave: "vph_dsadma", titulo: "Viviendas particulares que disponen de drenaje y sanitario con admisión de agua", sql: "SUM(x.vph_dsadma)", unidad: "viviendas", sumable: true },
  { clave: "vph_ndacmm", titulo: "Viviendas particulares habitadas que no disponen de automóvil o camioneta, ni de motocicleta o motoneta", sql: "SUM(x.vph_ndacmm)", unidad: "viviendas", sumable: true },
  { clave: "vph_snbien", titulo: "Viviendas particulares habitadas sin ningún bien", sql: "SUM(x.vph_snbien)", unidad: "viviendas", sumable: true },
  { clave: "vph_refri", titulo: "Viviendas particulares habitadas que disponen de refrigerador", sql: "SUM(x.vph_refri)", unidad: "viviendas", sumable: true },
  { clave: "vph_lavad", titulo: "Viviendas particulares habitadas que disponen de lavadora", sql: "SUM(x.vph_lavad)", unidad: "viviendas", sumable: true },
  { clave: "vph_hmicro", titulo: "Viviendas particulares habitadas que disponen de horno de microondas", sql: "SUM(x.vph_hmicro)", unidad: "viviendas", sumable: true },
  { clave: "vph_autom", titulo: "Viviendas particulares habitadas que disponen de automóvil o camioneta", sql: "SUM(x.vph_autom)", unidad: "viviendas", sumable: true },
  { clave: "vph_moto", titulo: "Viviendas particulares habitadas que disponen de motocicleta o motoneta", sql: "SUM(x.vph_moto)", unidad: "viviendas", sumable: true },
  { clave: "vph_bici", titulo: "Viviendas particulares habitadas que disponen de bicicleta como medio de transporte", sql: "SUM(x.vph_bici)", unidad: "viviendas", sumable: true },
  { clave: "vph_radio", titulo: "Viviendas particulares habitadas que disponen de radio", sql: "SUM(x.vph_radio)", unidad: "viviendas", sumable: true },
  { clave: "vph_tv", titulo: "Viviendas particulares habitadas que disponen de televisor", sql: "SUM(x.vph_tv)", unidad: "viviendas", sumable: true },
  { clave: "vph_pc", titulo: "Viviendas particulares habitadas que disponen de computadora, laptop o tablet", sql: "SUM(x.vph_pc)", unidad: "viviendas", sumable: true },
  { clave: "vph_telef", titulo: "Viviendas particulares habitadas que disponen de línea telefónica fija", sql: "SUM(x.vph_telef)", unidad: "viviendas", sumable: true },
  { clave: "vph_cel", titulo: "Viviendas particulares habitadas que disponen de teléfono celular", sql: "SUM(x.vph_cel)", unidad: "viviendas", sumable: true },
  { clave: "vph_inter", titulo: "Viviendas particulares habitadas que disponen de Internet", sql: "SUM(x.vph_inter)", unidad: "viviendas", sumable: true },
  { clave: "vph_stvp", titulo: "Viviendas particulares habitadas que disponen de servicio de televisión de paga", sql: "SUM(x.vph_stvp)", unidad: "viviendas", sumable: true },
  { clave: "vph_spmvpi", titulo: "Viviendas particulares habitadas que disponen de servicio de películas, música o videos de paga por Internet", sql: "SUM(x.vph_spmvpi)", unidad: "viviendas", sumable: true },
  { clave: "vph_cvj", titulo: "Viviendas particulares habitadas que disponen de consola de videojuegos", sql: "SUM(x.vph_cvj)", unidad: "viviendas", sumable: true },
  { clave: "vph_sinrtv", titulo: "Viviendas particulares habitadas sin radio ni televisor", sql: "SUM(x.vph_sinrtv)", unidad: "viviendas", sumable: true },
  { clave: "vph_sinltc", titulo: "Viviendas particulares habitadas sin línea telefónica fija ni teléfono celular", sql: "SUM(x.vph_sinltc)", unidad: "viviendas", sumable: true },
  { clave: "vph_sincint", titulo: "Viviendas particulares habitadas sin computadora ni Internet", sql: "SUM(x.vph_sincint)", unidad: "viviendas", sumable: true },
  { clave: "vph_sintic", titulo: "Viviendas particulares habitadas sin tecnologías de la información y de la comunicación (TIC)", sql: "SUM(x.vph_sintic)", unidad: "viviendas", sumable: true },  ],
  dimensiones: DIMS, predeterminado: { medidas: ["pea", "pocupada", "vivpar_hab"], columnas: ["entidad"] }, sql_corte: "SELECT '2020-03-15' AS corte", notas: NOTAS, api_dominio: "/api/v1/censo2020",
};
