// Cubo del Censo de Población y Vivienda 2020 por localidad (ITER): las 90 medidas de población de la tabla `iter`
// (títulos del diccionario del INEGI). El universo son las localidades (una fila por localidad); las filas de totales
// (loc 0000, mun 000) y los agregados de localidades de una y dos viviendas (loc 9998/9999, que repiten cifras ya
// contenidas en las localidades) se excluyen; así la suma por municipio y por entidad reproduce las filas totales del
// INEGI (verificado: Aguascalientes 1,425,607; país 126,014,024).
import type { Cubo } from "../tipos";

export const CENSO_ITER: Cubo = {
  clave: "censo2020-poblacion", nombre: "Población por localidad, municipio y entidad", tema: "poblacion", fuente: "INEGI — Censo de Población y Vivienda 2020, Principales resultados por localidad (ITER)", fuente_url: "https://www.inegi.org.mx/programas/ccpv/2020/", licencia: "Términos de libre uso INEGI",
  descripcion: "Población total, por sexo y por grupos de edad de cada localidad del país, sumable a municipio y entidad (jerarquía entidad › municipio › localidad).",
  binding: "DB_CENSO2020", desde: "iter", donde: "mun <> '000' AND loc NOT IN ('0000', '9998', '9999')",
  medidas: [
  { clave: "pobtot", titulo: "Población total", sql: "SUM(pobtot)", unidad: "personas", sumable: true },
  { clave: "pobfem", titulo: "Población femenina", sql: "SUM(pobfem)", unidad: "personas", sumable: true },
  { clave: "pobmas", titulo: "Población masculina", sql: "SUM(pobmas)", unidad: "personas", sumable: true },
  { clave: "p_0a2", titulo: "Población de 0 a 2 años", sql: "SUM(p_0a2)", unidad: "personas", sumable: true },
  { clave: "p_0a2_f", titulo: "Población femenina de 0 a 2 años", sql: "SUM(p_0a2_f)", unidad: "personas", sumable: true },
  { clave: "p_0a2_m", titulo: "Población masculina de 0 a 2 años", sql: "SUM(p_0a2_m)", unidad: "personas", sumable: true },
  { clave: "p_3ymas", titulo: "Población de 3 años y más", sql: "SUM(p_3ymas)", unidad: "personas", sumable: true },
  { clave: "p_3ymas_f", titulo: "Población femenina de 3 años y más", sql: "SUM(p_3ymas_f)", unidad: "personas", sumable: true },
  { clave: "p_3ymas_m", titulo: "Población masculina de 3 años y más", sql: "SUM(p_3ymas_m)", unidad: "personas", sumable: true },
  { clave: "p_5ymas", titulo: "Población de 5 años y más", sql: "SUM(p_5ymas)", unidad: "personas", sumable: true },
  { clave: "p_5ymas_f", titulo: "Población femenina de 5 años y más", sql: "SUM(p_5ymas_f)", unidad: "personas", sumable: true },
  { clave: "p_5ymas_m", titulo: "Población masculina de 5 años y más", sql: "SUM(p_5ymas_m)", unidad: "personas", sumable: true },
  { clave: "p_12ymas", titulo: "Población de 12 años y más", sql: "SUM(p_12ymas)", unidad: "personas", sumable: true },
  { clave: "p_12ymas_f", titulo: "Población femenina de 12 años y más", sql: "SUM(p_12ymas_f)", unidad: "personas", sumable: true },
  { clave: "p_12ymas_m", titulo: "Población masculina de 12 años y más", sql: "SUM(p_12ymas_m)", unidad: "personas", sumable: true },
  { clave: "p_15ymas", titulo: "Población de 15 años y más", sql: "SUM(p_15ymas)", unidad: "personas", sumable: true },
  { clave: "p_15ymas_f", titulo: "Población femenina de 15 años y más", sql: "SUM(p_15ymas_f)", unidad: "personas", sumable: true },
  { clave: "p_15ymas_m", titulo: "Población masculina de 15 años y más", sql: "SUM(p_15ymas_m)", unidad: "personas", sumable: true },
  { clave: "p_18ymas", titulo: "Población de 18 años y más", sql: "SUM(p_18ymas)", unidad: "personas", sumable: true },
  { clave: "p_18ymas_f", titulo: "Población femenina de 18 años y más", sql: "SUM(p_18ymas_f)", unidad: "personas", sumable: true },
  { clave: "p_18ymas_m", titulo: "Población masculina de 18 años y más", sql: "SUM(p_18ymas_m)", unidad: "personas", sumable: true },
  { clave: "p_3a5", titulo: "Población de 3 a 5 años", sql: "SUM(p_3a5)", unidad: "personas", sumable: true },
  { clave: "p_3a5_f", titulo: "Población femenina de 3 a 5 años", sql: "SUM(p_3a5_f)", unidad: "personas", sumable: true },
  { clave: "p_3a5_m", titulo: "Población masculina de 3 a 5 años", sql: "SUM(p_3a5_m)", unidad: "personas", sumable: true },
  { clave: "p_6a11", titulo: "Población de 6 a 11 años", sql: "SUM(p_6a11)", unidad: "personas", sumable: true },
  { clave: "p_6a11_f", titulo: "Población femenina de 6 a 11 años", sql: "SUM(p_6a11_f)", unidad: "personas", sumable: true },
  { clave: "p_6a11_m", titulo: "Población masculina de 6 a 11 años", sql: "SUM(p_6a11_m)", unidad: "personas", sumable: true },
  { clave: "p_8a14", titulo: "Población de 8 a 14 años", sql: "SUM(p_8a14)", unidad: "personas", sumable: true },
  { clave: "p_8a14_f", titulo: "Población femenina de 8 a 14 años", sql: "SUM(p_8a14_f)", unidad: "personas", sumable: true },
  { clave: "p_8a14_m", titulo: "Población masculina de 8 a 14 años", sql: "SUM(p_8a14_m)", unidad: "personas", sumable: true },
  { clave: "p_12a14", titulo: "Población de 12 a 14 años", sql: "SUM(p_12a14)", unidad: "personas", sumable: true },
  { clave: "p_12a14_f", titulo: "Población femenina de 12 a 14 años", sql: "SUM(p_12a14_f)", unidad: "personas", sumable: true },
  { clave: "p_12a14_m", titulo: "Población masculina de 12 a 14 años", sql: "SUM(p_12a14_m)", unidad: "personas", sumable: true },
  { clave: "p_15a17", titulo: "Población de 15 a 17 años", sql: "SUM(p_15a17)", unidad: "personas", sumable: true },
  { clave: "p_15a17_f", titulo: "Población femenina de 15 a 17 años", sql: "SUM(p_15a17_f)", unidad: "personas", sumable: true },
  { clave: "p_15a17_m", titulo: "Población masculina de 15 a 17 años", sql: "SUM(p_15a17_m)", unidad: "personas", sumable: true },
  { clave: "p_18a24", titulo: "Población de 18 a 24 años", sql: "SUM(p_18a24)", unidad: "personas", sumable: true },
  { clave: "p_18a24_f", titulo: "Población femenina de 18 a 24 años", sql: "SUM(p_18a24_f)", unidad: "personas", sumable: true },
  { clave: "p_18a24_m", titulo: "Población masculina de 18 a 24 años", sql: "SUM(p_18a24_m)", unidad: "personas", sumable: true },
  { clave: "p_15a49_f", titulo: "Población femenina de 15 a 49 años", sql: "SUM(p_15a49_f)", unidad: "personas", sumable: true },
  { clave: "p_60ymas", titulo: "Población de 60 años y más", sql: "SUM(p_60ymas)", unidad: "personas", sumable: true },
  { clave: "p_60ymas_f", titulo: "Población femenina de 60 años y más", sql: "SUM(p_60ymas_f)", unidad: "personas", sumable: true },
  { clave: "p_60ymas_m", titulo: "Población masculina de 60 años y más", sql: "SUM(p_60ymas_m)", unidad: "personas", sumable: true },
  { clave: "pob0_14", titulo: "Población de 0 a 14 años", sql: "SUM(pob0_14)", unidad: "personas", sumable: true },
  { clave: "pob15_64", titulo: "Población de 15 a 64 años", sql: "SUM(pob15_64)", unidad: "personas", sumable: true },
  { clave: "pob65_mas", titulo: "Población de 65 años y más", sql: "SUM(pob65_mas)", unidad: "personas", sumable: true },
  { clave: "p_0a4", titulo: "Población de 0 a 4 años", sql: "SUM(p_0a4)", unidad: "personas", sumable: true },
  { clave: "p_0a4_f", titulo: "Población femenina de 0 a 4 años", sql: "SUM(p_0a4_f)", unidad: "personas", sumable: true },
  { clave: "p_0a4_m", titulo: "Población masculina de 0 a 4 años", sql: "SUM(p_0a4_m)", unidad: "personas", sumable: true },
  { clave: "p_5a9", titulo: "Población de 5 a 9 años", sql: "SUM(p_5a9)", unidad: "personas", sumable: true },
  { clave: "p_5a9_f", titulo: "Población femenina de 5 a 9 años", sql: "SUM(p_5a9_f)", unidad: "personas", sumable: true },
  { clave: "p_5a9_m", titulo: "Población masculina de 5 a 9 años", sql: "SUM(p_5a9_m)", unidad: "personas", sumable: true },
  { clave: "p_10a14", titulo: "Población de 10 a 14 años", sql: "SUM(p_10a14)", unidad: "personas", sumable: true },
  { clave: "p_10a14_f", titulo: "Población femenina de 10 a 14 años", sql: "SUM(p_10a14_f)", unidad: "personas", sumable: true },
  { clave: "p_10a14_m", titulo: "Población masculina de 10 a 14 años", sql: "SUM(p_10a14_m)", unidad: "personas", sumable: true },
  { clave: "p_15a19", titulo: "Población de 15 a 19 años", sql: "SUM(p_15a19)", unidad: "personas", sumable: true },
  { clave: "p_15a19_f", titulo: "Población femenina de 15 a 19 años", sql: "SUM(p_15a19_f)", unidad: "personas", sumable: true },
  { clave: "p_15a19_m", titulo: "Población masculina de 15 a 19 años", sql: "SUM(p_15a19_m)", unidad: "personas", sumable: true },
  { clave: "p_20a24", titulo: "Población de 20 a 24 años", sql: "SUM(p_20a24)", unidad: "personas", sumable: true },
  { clave: "p_20a24_f", titulo: "Población femenina de 20 a 24 años", sql: "SUM(p_20a24_f)", unidad: "personas", sumable: true },
  { clave: "p_20a24_m", titulo: "Población masculina de 20 a 24 años", sql: "SUM(p_20a24_m)", unidad: "personas", sumable: true },
  { clave: "p_25a29", titulo: "Población de 25 a 29 años", sql: "SUM(p_25a29)", unidad: "personas", sumable: true },
  { clave: "p_25a29_f", titulo: "Población femenina de 25 a 29 años", sql: "SUM(p_25a29_f)", unidad: "personas", sumable: true },
  { clave: "p_25a29_m", titulo: "Población masculina de 25 a 29 años", sql: "SUM(p_25a29_m)", unidad: "personas", sumable: true },
  { clave: "p_30a34", titulo: "Población de 30 a 34 años", sql: "SUM(p_30a34)", unidad: "personas", sumable: true },
  { clave: "p_30a34_f", titulo: "Población femenina de 30 a 34 años", sql: "SUM(p_30a34_f)", unidad: "personas", sumable: true },
  { clave: "p_30a34_m", titulo: "Población masculina de 30 a 34 años", sql: "SUM(p_30a34_m)", unidad: "personas", sumable: true },
  { clave: "p_35a39", titulo: "Población de 35 a 39 años", sql: "SUM(p_35a39)", unidad: "personas", sumable: true },
  { clave: "p_35a39_f", titulo: "Población femenina de 35 a 39 años", sql: "SUM(p_35a39_f)", unidad: "personas", sumable: true },
  { clave: "p_35a39_m", titulo: "Población masculina de 35 a 39 años", sql: "SUM(p_35a39_m)", unidad: "personas", sumable: true },
  { clave: "p_40a44", titulo: "Población de 40 a 44 años", sql: "SUM(p_40a44)", unidad: "personas", sumable: true },
  { clave: "p_40a44_f", titulo: "Población femenina de 40 a 44 años", sql: "SUM(p_40a44_f)", unidad: "personas", sumable: true },
  { clave: "p_40a44_m", titulo: "Población masculina de 40 a 44 años", sql: "SUM(p_40a44_m)", unidad: "personas", sumable: true },
  { clave: "p_45a49", titulo: "Población de 45 a 49 años", sql: "SUM(p_45a49)", unidad: "personas", sumable: true },
  { clave: "p_45a49_f", titulo: "Población femenina de 45 a 49 años", sql: "SUM(p_45a49_f)", unidad: "personas", sumable: true },
  { clave: "p_45a49_m", titulo: "Población masculina de 45 a 49 años", sql: "SUM(p_45a49_m)", unidad: "personas", sumable: true },
  { clave: "p_50a54", titulo: "Población de 50 a 54 años", sql: "SUM(p_50a54)", unidad: "personas", sumable: true },
  { clave: "p_50a54_f", titulo: "Población femenina de 50 a 54 años", sql: "SUM(p_50a54_f)", unidad: "personas", sumable: true },
  { clave: "p_50a54_m", titulo: "Población masculina de 50 a 54 años", sql: "SUM(p_50a54_m)", unidad: "personas", sumable: true },
  { clave: "p_55a59", titulo: "Población de 55 a 59 años", sql: "SUM(p_55a59)", unidad: "personas", sumable: true },
  { clave: "p_55a59_f", titulo: "Población femenina de 55 a 59 años", sql: "SUM(p_55a59_f)", unidad: "personas", sumable: true },
  { clave: "p_55a59_m", titulo: "Población masculina de 55 a 59 años", sql: "SUM(p_55a59_m)", unidad: "personas", sumable: true },
  { clave: "p_60a64", titulo: "Población de 60 a 64 años", sql: "SUM(p_60a64)", unidad: "personas", sumable: true },
  { clave: "p_60a64_f", titulo: "Población femenina de 60 a 64 años", sql: "SUM(p_60a64_f)", unidad: "personas", sumable: true },
  { clave: "p_60a64_m", titulo: "Población masculina de 60 a 64 años", sql: "SUM(p_60a64_m)", unidad: "personas", sumable: true },
  { clave: "p_65a69", titulo: "Población de 65 a 69 años", sql: "SUM(p_65a69)", unidad: "personas", sumable: true },
  { clave: "p_65a69_f", titulo: "Población femenina de 65 a 69 años", sql: "SUM(p_65a69_f)", unidad: "personas", sumable: true },
  { clave: "p_65a69_m", titulo: "Población masculina de 65 a 69 años", sql: "SUM(p_65a69_m)", unidad: "personas", sumable: true },
  { clave: "p_70a74", titulo: "Población de 70 a 74 años", sql: "SUM(p_70a74)", unidad: "personas", sumable: true },
  { clave: "p_70a74_f", titulo: "Población femenina de 70 a 74 años", sql: "SUM(p_70a74_f)", unidad: "personas", sumable: true },    { clave: "localidades", titulo: "Localidades", sql: "COUNT(*)", unidad: "localidades", sumable: true },
  ],
  dimensiones: [
    { clave: "entidad", titulo: "Entidad", id: "entidad", nombre: "nom_ent", tipo: "geografica", geo: "entidad" },
    { clave: "municipio", titulo: "Municipio", id: "entidad || mun", nombre: "nom_mun", tipo: "geografica", geo: "municipio", padre: "entidad", descripcion: "Clave de 5 dígitos (entidad + municipio)." },
    { clave: "localidad", titulo: "Localidad", id: "entidad || mun || loc", nombre: "nom_loc", tipo: "geografica", geo: "localidad", padre: "municipio", descripcion: "Clave de 9 dígitos (entidad + municipio + localidad)." },
    { clave: "tamano", titulo: "Tamaño de localidad", id: "CASE WHEN pobtot < 2500 THEN 'Menos de 2,500' WHEN pobtot < 15000 THEN '2,500 a 14,999' WHEN pobtot < 100000 THEN '15,000 a 99,999' ELSE '100,000 y más' END", tipo: "categorica", orden: "MIN(pobtot)", descripcion: "Rangos de población total de la localidad (los del INEGI para rural/urbano: 2,500 y 15,000)." },
  ],
  predeterminado: { medidas: ["pobtot", "pobfem", "pobmas"], columnas: ["entidad"] },
  sql_corte: "SELECT '2020-03-15' AS corte",
  notas: ["Una fila por localidad. Las filas de totales del ITER (entidad, municipio) y los agregados de localidades de una y dos viviendas (claves 9998 y 9999, que repiten cifras ya contenidas en las localidades) no forman parte del universo; por eso las sumas reproducen los totales oficiales.", "Valores confidenciales (*) y no aplicables del ITER se conservan como nulos y no suman."],
  api_dominio: "/api/v1/censo2020",
};
