// Cubo de los Censos Económicos 2004-2024 (scripts/ce_datos_abiertos.py + saic_cargar.py): las nueve variables principales para
// el nacional y las entidades (saic_a, que con saic_b guarda las 98) y para los municipios (saic_mun, 1.0-1.8 M de filas por
// censo; las 98 municipales están en el Parquet de /api/v1/inegi/saic/descarga/{año}). Nivel de actividad y estrato son
// particiones (el total contiene a los sectores; la suma de estratos contiene a cada estrato): toda consulta los filtra o los lleva en columnas.
import type { Cubo } from "../tipos";
const MED = (col: string, titulo: string, unidad: string) => ({ clave: col.toLowerCase(), titulo, sql: `SUM(h.${col})`, unidad, descripcion: `Variable ${col} del SAIC`, sumable: true, decimales: unidad === "unidades" || unidad === "personas" ? 0 : 3 });
export const SAIC_CENSOS: Cubo = {
  clave: "saic-censos", nombre: "Censos Económicos 2004-2024 por municipio, actividad y estrato", tema: "economia", fuente: "INEGI — Censos Económicos 2004-2024, datos abiertos (el mismo cuadro que sirve el SAIC)", fuente_url: "https://www.inegi.org.mx/programas/ce/2024/#datos_abiertos", licencia: "Términos de libre uso INEGI",
  descripcion: "Unidades económicas, personal ocupado, remuneraciones, producción bruta, valor agregado y activos de los cinco Censos Económicos (2004, 2009, 2014, 2019 y 2024) por entidad, municipio, actividad (total, sector, subsector, rama, subrama y clase del SCIAN) y estrato de personal ocupado: el cuadro completo que publica el INEGI como datos abiertos y que sirve su SAIC.",
  binding: "DB_CENSO2020", desde: "(SELECT anio, cve_ent, cve_mun, nivel_act, clave_act, estrato, UE, H001A, J000A, A111A, A131A, A221A, Q000A, M000A, K000A FROM saic_a UNION ALL SELECT anio, cve_ent, cve_mun, nivel_act, clave_act, estrato, UE, H001A, J000A, A111A, A131A, A221A, Q000A, M000A, K000A FROM saic_mun) h LEFT JOIN saic_actividades x ON x.clave = h.clave_act LEFT JOIN saic_estratos s ON s.cod = h.estrato LEFT JOIN saic_entidades en ON en.cve_ent = h.cve_ent",
  medidas: [MED("UE", "Unidades económicas", "unidades"), MED("H001A", "Personal ocupado total", "personas"), MED("J000A", "Remuneraciones", "millones de pesos"), MED("A111A", "Producción bruta total", "millones de pesos"), MED("A131A", "Valor agregado censal bruto", "millones de pesos"), MED("A221A", "Formación bruta de capital fijo", "millones de pesos"), MED("Q000A", "Acervo total de activos fijos", "millones de pesos"), MED("M000A", "Ingresos por suministro de bienes y servicios", "millones de pesos"), MED("K000A", "Gastos por consumo de bienes y servicios", "millones de pesos")],
  dimensiones: [
    { clave: "anio", titulo: "Año censal", id: "h.anio", nombre: "'Censos Económicos ' || (CAST(h.anio AS INTEGER) + 1) || ' (datos ' || h.anio || ')'", tipo: "temporal", orden: "1", miembros: { desde: "saic_anios y", id: "y.anio", nombre: "y.censo || ' (datos ' || y.anio || ')'", orden: "y.anio" } },
    { clave: "ambito", titulo: "Ámbito geográfico", id: "CASE WHEN h.cve_ent = '00' THEN 'nacional' WHEN h.cve_mun = '' THEN 'entidad' ELSE 'municipio' END", tipo: "categorica", orden: "CASE WHEN h.cve_ent = '00' THEN 1 WHEN h.cve_mun = '' THEN 2 ELSE 3 END", particion: { implicita_en: ["entidad", "municipio"] }, descripcion: "nacional, entidad o municipio: los tres contienen a las mismas unidades; toda consulta filtra uno o agrupa por él (o por geografía).", miembros: { desde: "(SELECT 'nacional' AS a UNION ALL SELECT 'entidad' UNION ALL SELECT 'municipio') x", id: "x.a", nombre: "x.a", orden: "CASE x.a WHEN 'nacional' THEN 1 WHEN 'entidad' THEN 2 ELSE 3 END" } },
    { clave: "entidad", titulo: "Entidad", id: "h.cve_ent", nombre: "en.nombre", tipo: "geografica", geo: "entidad", orden: "1" },
    { clave: "municipio", titulo: "Municipio", id: "h.cve_ent || h.cve_mun", tipo: "geografica", geo: "municipio", padre: "entidad", orden: "1", descripcion: "Clave de municipio; el nombre está en /api/v1/geo/municipios." },
    { clave: "nivel", titulo: "Nivel de actividad", id: "h.nivel_act", nombre: "CASE h.nivel_act WHEN 0 THEN 'Total' WHEN 1 THEN 'Sector' WHEN 2 THEN 'Subsector' WHEN 3 THEN 'Rama' WHEN 4 THEN 'Subrama' ELSE 'Clase' END", tipo: "categorica", orden: "1", particion: { implicita_en: ["actividad"] }, descripcion: "El total contiene a los sectores y estos a sus subsectores: toda consulta filtra un nivel o agrupa por actividad.", miembros: { desde: "(SELECT 0 AS n, 'Total' AS t UNION ALL SELECT 1, 'Sector' UNION ALL SELECT 2, 'Subsector' UNION ALL SELECT 3, 'Rama' UNION ALL SELECT 4, 'Subrama' UNION ALL SELECT 5, 'Clase') x", id: "x.n", nombre: "x.t", orden: "x.n" } },
    { clave: "actividad", titulo: "Actividad económica (SCIAN)", id: "h.clave_act", nombre: "x.nombre", tipo: "categorica", orden: "1", miembros: { desde: "saic_actividades x", id: "x.clave", nombre: "x.nombre", orden: "x.nivel, x.clave" } },
    { clave: "estrato", titulo: "Estrato de personal ocupado", id: "h.estrato", nombre: "s.nombre", tipo: "categorica", orden: "1", particion: {}, descripcion: "0 = suma de estratos (contiene a los demás): toda consulta filtra un estrato o agrupa por él.", miembros: { desde: "saic_estratos s", id: "s.cod", nombre: "s.nombre", orden: "s.cod" } },
  ],
  predeterminado: { medidas: ["ue", "h001a"], columnas: ["actividad"], filtros: { anio: ["2023"], ambito: ["nacional"], nivel: ["1"], estrato: ["0"] } },
  sql_corte: "SELECT MAX(anio) AS corte FROM saic_anios",
  notas: ["Los Censos Económicos no cubren las actividades agropecuarias ni forestales (subsector 115 sí). Valores nulos = el INEGI no publica el dato por confidencialidad o no aplica.", "Millones de pesos corrientes de cada censo. Los cinco censos están completos: nacional, 32 entidades y todos los municipios de cada censo, en los seis niveles de actividad y los seis estratos. Las unidades económicas municipales suman exactamente la entidad; las demás variables (personal ocupado, valor agregado…) las deja vacías el INEGI por confidencialidad donde hay pocas unidades (unos dos tercios de las filas municipales en cada censo), así que su suma municipal queda por debajo de la cifra de la entidad.", "Verificación: los datos abiertos coinciden celda por celda con lo que entrega la API del SAIC (33.6 millones de celdas cotejadas, diferencia máxima 0.00055 por el redondeo del SAIC), y las unidades económicas nacionales son las del indicador 5300000001 del Banco de Indicadores.", "Las 98 variables (personal por sexo, horas, salarios, inventarios, activos por tipo…) están en /api/v1/inegi/saic/datos para el nacional y las entidades, y para todo, municipios incluidos, en el Parquet por año de /api/v1/inegi/saic/descarga/{año}."],
  filtro_obligatorio: ["anio"],
  api_dominio: "/api/v1/inegi/saic",
};
