// Constantes del router ENOE del legacy, verbatim.
export const SOURCE_ENOE = "INEGI — Encuesta Nacional de Ocupación y Empleo (ENOE 15+). https://www.inegi.org.mx/programas/enoe/15ymas/";
export const SOURCE_RECONS_VARIABLES = "INEGI — ENOE Reconstrucción de variables 2023. https://www.inegi.org.mx/contenidos/programas/enoe/15ymas/doc/recons_var_15ymas.pdf";
export const URL_ENOE = "https://www.inegi.org.mx/programas/enoe/15ymas/";

export type Caveat = { slug: string; titulo: string; descripcion: string; periodo_aplicable: string; referencia: string };
export const CAVEAT_DOMINIO_15PLUS: Caveat = { slug: "dominio_15_plus", titulo: "Dominio operativo de la serie: población de 15 años o más", descripcion: "El observatorio reporta indicadores con dominio 15+ uniformemente en toda la serie. INEGI publicó originalmente la etapa clasica (2005T1-2020T1) con dominio 14+ siguiendo el marco legal pre-2014. El ENOE-N (2020T3+) ya nace con 15+ post-reforma constitucional 2014. Re-cálculo con 15+ en pre-2020T3 mantiene comparabilidad longitudinal.", periodo_aplicable: "2005T1-2020T1 (recálculo 15+)", referencia: "Boletín INEGI 209/15 — Reforma constitucional 2014" };
export const CAVEAT_ETAPA_CAMBIO_MARCO: Caveat = { slug: "cambio_marco_2020T3", titulo: "Cambio de marco muestral en 2020T3 (post-Censo 2020)", descripcion: "Series que cruzan 2020T2/2020T3 deben interpretarse considerando el rediseño del marco muestral post-Censo 2020. Pre-2020T3 usa marco pre-Censo 2020 (etapa 'clasica'); post-2020T3 usa marco post-Censo 2020 (etapa 'enoe_n'). El 2020T3-2021T4 conserva factores fac_tri pre-CPV-2020 → subestimación de 6-7% en conteos absolutos respecto a publicaciones posteriores. Las tasas (cocientes razón) no se ven afectadas por este artefacto.", periodo_aplicable: "2020T3-2021T4 (subestimación absolutos)", referencia: "Boletín INEGI 280/21" };
export const CAVEAT_GAP_2020T2: Caveat = { slug: "gap_2020T2_etoe", titulo: "Gap 2020T2: ETOE telefónica sustituye al ENOE presencial (COVID-19)", descripcion: "INEGI sustituyó el ENOE presencial por la Encuesta Telefónica de Ocupación y Empleo (ETOE) durante el 2020T2 por la pandemia COVID-19. La ETOE NO publicó microdatos descargables, solo agregados en la sección de investigación. El observatorio omite 2020T2 por asimetría metodológica (decisión D2b documentada en docs internos). Series con 'desde<=2020T2<=hasta' tendrán un gap de 1 trimestre.", periodo_aplicable: "2020T2 (1 trimestre omitido)", referencia: "Comunicado INEGI ETOE — Acervo Información Investigación" };
export const CAVEAT_TIL1_INFORMALIDAD: Caveat = { slug: "til1_definicion_operativa", titulo: "Tasa de Informalidad Laboral TIL1: 7 condiciones operativas", descripcion: "TIL1 se deriva en runtime desde 7 condiciones unidas con OR sobre tue2, pos_ocu, rama, seg_soc, remune2c (esta última vive en extras_jsonb por no estar typed). Sección 3.36 INEGI Reconstrucción de variables 2023.", periodo_aplicable: "Todos los periodos", referencia: SOURCE_RECONS_VARIABLES };
export const CAVEAT_TCCO_REDEFINICION: Caveat = { slug: "tcco_redefinicion_2020", titulo: "TCCO (Condiciones Críticas de Ocupación): 3 condiciones operativas", descripcion: "INEGI ajustó la definición operativa de TCCO en el rediseño 2020. El observatorio calcula TCCO con el dominio 3-condiciones documentado en sec 3.24 INEGI Reconstrucción de variables 2023, aplicable a toda la serie. Series TCCO 2005-2019 no son comparables 1:1 con publicaciones INEGI pre-2020 que usaban definición previa.", periodo_aplicable: "Pre-2020T3 (comparación con publicaciones INEGI originales)", referencia: `${SOURCE_RECONS_VARIABLES} (sec 3.24)` };
export const CAVEATS_GLOBALES: Caveat[] = [CAVEAT_DOMINIO_15PLUS, CAVEAT_ETAPA_CAMBIO_MARCO, CAVEAT_GAP_2020T2, CAVEAT_TIL1_INFORMALIDAD, CAVEAT_TCCO_REDEFINICION];
export const CAVEATS_BY_SLUG = new Map(CAVEATS_GLOBALES.map((c) => [c.slug, c]));

export type IndicadorDef = { slug: string; nombre: string; descripcion: string; unidad: string; categoria: string; formula: string; caveat_slug: string | null };
export const INDICADORES_DEFS: IndicadorDef[] = [
  { slug: "pob_15ymas", nombre: "Población de 15 años o más", descripcion: "Universo de referencia del ENOE 15+ (población en edad de trabajar = PEA + PNEA, como la publica el INEGI). Suma expandida vía fac_tri.", unidad: "personas", categoria: "conteo", formula: "SUM(fac_tri) WHERE eda >= 15 AND clase1 IN (1, 2)", caveat_slug: "dominio_15_plus" },
  { slug: "pea_total", nombre: "Población Económicamente Activa (PEA)", descripcion: "Personas 15+ ocupadas o buscando empleo (clase1=1).", unidad: "personas", categoria: "conteo", formula: "SUM(fac_tri) WHERE eda >= 15 AND clase1 = 1", caveat_slug: null },
  { slug: "pnea_total", nombre: "Población No Económicamente Activa (PNEA)", descripcion: "Personas 15+ que no participan en el mercado laboral (clase1=2).", unidad: "personas", categoria: "conteo", formula: "SUM(fac_tri) WHERE eda >= 15 AND clase1 = 2", caveat_slug: null },
  { slug: "ocupados_total", nombre: "Población ocupada", descripcion: "Personas 15+ con trabajo (clase2=1).", unidad: "personas", categoria: "conteo", formula: "SUM(fac_tri) WHERE clase2 = 1", caveat_slug: null },
  { slug: "desocupados_total", nombre: "Población desocupada", descripcion: "Personas 15+ sin trabajo, buscando empleo (clase2=2).", unidad: "personas", categoria: "conteo", formula: "SUM(fac_tri) WHERE clase2 = 2", caveat_slug: null },
  { slug: "subocupados_total", nombre: "Población subocupada", descripcion: "Ocupados disponibles para trabajar más horas (sub_o=1).", unidad: "personas", categoria: "conteo", formula: "SUM(fac_tri) WHERE clase2 = 1 AND sub_o = 1", caveat_slug: null },
  { slug: "condcrit_total", nombre: "Ocupados en condiciones críticas (TCCO)", descripcion: "Ocupados con al menos una de 3 condiciones críticas (tcco in 1,2,3).", unidad: "personas", categoria: "conteo", formula: "SUM(fac_tri) WHERE clase2 = 1 AND tcco IN (1, 2, 3)", caveat_slug: "tcco_redefinicion_2020" },
  { slug: "informales_total", nombre: "Ocupados informales (TIL1 base)", descripcion: "Ocupados informales según TIL1 (7 condiciones operativas sobre tue2/pos_ocu/rama/seg_soc/remune2c).", unidad: "personas", categoria: "conteo", formula: "SUM(fac_tri) WHERE clase2 = 1 AND TIL1_predicado", caveat_slug: "til1_definicion_operativa" },
  { slug: "tasa_participacion", nombre: "Tasa de Participación", descripcion: "Porcentaje de la población 15+ que está económicamente activa.", unidad: "porcentaje", categoria: "tasa", formula: "100 × PEA / Pob15+", caveat_slug: "dominio_15_plus" },
  { slug: "tasa_desocupacion", nombre: "Tasa de Desocupación", descripcion: "Porcentaje de la PEA sin empleo.", unidad: "porcentaje", categoria: "tasa", formula: "100 × Desocupados / PEA", caveat_slug: null },
  { slug: "tasa_subocupacion", nombre: "Tasa de Subocupación", descripcion: "Porcentaje de ocupados disponibles para trabajar más horas.", unidad: "porcentaje", categoria: "tasa", formula: "100 × Subocupados / Ocupados", caveat_slug: null },
  { slug: "tasa_informalidad_til1", nombre: "Tasa de Informalidad Laboral (TIL1)", descripcion: "Porcentaje de ocupados en condición de informalidad según TIL1 (sec 3.36 INEGI Reconstrucción de variables 2023).", unidad: "porcentaje", categoria: "tasa", formula: "100 × Informales / Ocupados", caveat_slug: "til1_definicion_operativa" },
  { slug: "tasa_ocupacion_critica_tcco", nombre: "Tasa de Condiciones Críticas de Ocupación (TCCO)", descripcion: "Porcentaje de ocupados con al menos una de 3 condiciones críticas (sec 3.24 INEGI Reconstrucción de variables 2023).", unidad: "porcentaje", categoria: "tasa", formula: "100 × Ocupados_TCCO / Ocupados", caveat_slug: "tcco_redefinicion_2020" },
];
export const INDICADOR_BY_SLUG = new Map(INDICADORES_DEFS.map((d) => [d.slug, d]));
export const INDICADORES_CONTEO = new Set(INDICADORES_DEFS.filter((d) => d.categoria === "conteo").map((d) => d.slug));
export const INDICADORES_SENSIBLES_DOMINIO = new Set(["pob_15ymas", "pea_total", "pnea_total", "tasa_participacion"]);

export type Etapa = { slug: string; nombre: string; descripcion: string; periodo_inicio: string; periodo_fin: string | null; dominio_edad: string; n_trimestres: number; tiene_microdatos: boolean; caveat_aplicable: string | null };
export const ETAPAS_DEFS: Etapa[] = [
  { slug: "clasica", nombre: "ENOE Clásica (pre-rediseño)", descripcion: "Diseño 2005-2020T1 con marco muestral pre-Censo 2020. Población originalmente publicada con dominio 14+; el observatorio re-calcula con dominio 15+ para comparabilidad longitudinal.", periodo_inicio: "2005T1", periodo_fin: "2020T1", dominio_edad: "15+ (recálculo); publicación original 14+", n_trimestres: 61, tiene_microdatos: true, caveat_aplicable: "Para comparaciones largas que cruzan 2020T2/2020T3, considerar cambio de marco muestral post-Censo 2020 (slug 'cambio_marco_2020T3')." },
  { slug: "etoe_telefonica", nombre: "ETOE (Encuesta Telefónica) — COVID-19", descripcion: "Diseño emergente 2020T2: encuesta telefónica sustituta del ENOE presencial durante el confinamiento pandémico. INEGI no publicó microdatos descargables; solo agregados de investigación. El observatorio omite este trimestre por asimetría metodológica.", periodo_inicio: "2020T2", periodo_fin: "2020T2", dominio_edad: "15+", n_trimestres: 1, tiene_microdatos: false, caveat_aplicable: "Sin microdatos descargables. Etapa registrada para completeness documental. Series ENOE saltan de 2020T1 a 2020T3." },
  { slug: "enoe_n", nombre: "ENOE-N (Nueva Edición, post-Censo 2020)", descripcion: "Diseño actual desde 2020T3 con marco muestral rediseñado post-Censo 2020. Población 15+ uniformemente. Incluye URL legacy enoe_n_* (2020T3-2022T4) y enoe_* (2023T1+), rebranding nominal sin cambio metodológico.", periodo_inicio: "2020T3", periodo_fin: null, dominio_edad: "15+", n_trimestres: 19, tiene_microdatos: true, caveat_aplicable: "2020T3-2021T4: fac_tri pre-CPV-2020 produce subestimación 6-7% en conteos absolutos (no afecta tasas). Slug 'cambio_marco_2020T3'." },
];
export const TABLA_DESCRIPCIONES: [string, string][] = [
  ["microdatos_viv", "Microdatos de Vivienda (cuestionario residencial)"],
  ["microdatos_hog", "Microdatos de Hogar (cuestionario doméstico)"],
  ["microdatos_sdem", "Microdatos Sociodemográficos (fuente operativa de los indicadores)"],
  ["microdatos_coe1", "Cuestionario de Ocupación y Empleo, parte 1"],
  ["microdatos_coe2", "Cuestionario de Ocupación y Empleo, parte 2"],
  ["indicadores_nacionales", "Indicadores agregados a nivel nacional"],
  ["indicadores_entidad", "Indicadores agregados por entidad federativa"],
  ["indicadores_area_metropolitana", "Indicadores por área metropolitana (schema-ready, pendiente Fase 4)"],
  ["indicadores_anuales_ampliado", "Indicadores anuales del cuestionario ampliado (solo T1, schema-ready)"],
  ["poblacion_ocupada_por_sector", "Cortes de ocupados por sector económico (rama_est2, 11 sectores SCIAN agregados + categoría '0' no especificado)"],
  ["poblacion_ocupada_por_posicion", "Cortes de ocupados por posición en la ocupación (pos_ocu)"],
];
export const SCHEMA_READY = new Set(["indicadores_area_metropolitana", "indicadores_anuales_ampliado"]);
export const SECTOR_NOMBRE = new Map<string, string>([["0", "No especificado"], ["1", "Agricultura, ganadería, silvicultura, caza y pesca"], ["2", "Industria extractiva y de la electricidad"], ["3", "Industria manufacturera"], ["4", "Construcción"], ["5", "Comercio"], ["6", "Restaurantes y servicios de alojamiento"], ["7", "Transportes, comunicaciones, correo y almacenamiento"], ["8", "Servicios profesionales, financieros y corporativos"], ["9", "Servicios sociales"], ["10", "Servicios diversos"], ["11", "Gobierno y organismos internacionales"]]);
export const POSICION_NOMBRE = new Map<number, string>([[1, "Trabajadores subordinados y remunerados"], [2, "Empleadores"], [3, "Trabajadores por cuenta propia"], [4, "Trabajadores no remunerados"]]);
